# Generated by Django 4.2.4 on 2024-03-25 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
                ('source', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr', models.TextField(blank=True, null=True)),
                ('en', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RootChars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin', models.CharField(blank=True, max_length=5, null=True)),
                ('arabic', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('name_en', models.CharField(blank=True, max_length=20, null=True)),
                ('name_original', models.CharField(blank=True, max_length=50, null=True)),
                ('name_translation_tr', models.CharField(blank=True, max_length=30, null=True)),
                ('name_translation_en', models.CharField(blank=True, max_length=30, null=True)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('surah_number', models.IntegerField()),
                ('verse_count', models.IntegerField()),
                ('page_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_number', models.IntegerField(blank=True, null=True)),
                ('transcription_tr', models.CharField(blank=True, max_length=20, null=True)),
                ('transcription_en', models.CharField(blank=True, max_length=20, null=True)),
                ('arabic', models.CharField(blank=True, max_length=20, null=True)),
                ('translation_tr', models.CharField(blank=True, max_length=20, null=True)),
                ('translation_en', models.CharField(blank=True, max_length=20, null=True)),
                ('word_detail', models.ManyToManyField(blank=True, to='book.detail', verbose_name='details')),
            ],
        ),
        migrations.CreateModel(
            name='VerseZero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_number', models.IntegerField()),
                ('verse', models.TextField()),
                ('verse_simplified', models.TextField(blank=True, null=True)),
                ('verse_without_vowel', models.TextField(blank=True, null=True)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('transcription_en', models.TextField(blank=True, null=True)),
                ('page_number', models.IntegerField()),
                ('juz_number', models.IntegerField()),
                ('verse_word', models.ManyToManyField(to='book.word', verbose_name='words')),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_number', models.IntegerField()),
                ('verse', models.TextField()),
                ('verse_simplified', models.TextField(blank=True, null=True)),
                ('verse_without_vowel', models.TextField(blank=True, null=True)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('transcription_en', models.TextField(blank=True, null=True)),
                ('page_number', models.IntegerField()),
                ('juz_number', models.IntegerField()),
                ('related_surah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.surah', verbose_name='verses')),
                ('verse_word', models.ManyToManyField(to='book.word', verbose_name='words')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author', verbose_name='authors')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='book.verse')),
            ],
        ),
        migrations.AddField(
            model_name='surah',
            name='zero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.versezero', verbose_name='zero_verse'),
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin', models.CharField(blank=True, max_length=20, null=True)),
                ('arabic', models.CharField(blank=True, max_length=30, null=True)),
                ('transcription', models.CharField(blank=True, max_length=50, null=True)),
                ('transcription_en', models.CharField(blank=True, max_length=50, null=True)),
                ('mean', models.TextField(blank=True, null=True)),
                ('mean_en', models.TextField(blank=True, null=True)),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.word', verbose_name='words')),
            ],
        ),
        migrations.CreateModel(
            name='Footnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('translation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.translation', verbose_name='translations')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp3', models.URLField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('voiced_by', models.CharField(blank=True, max_length=50, null=True)),
                ('related_surah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.surah', verbose_name='audios')),
            ],
        ),
    ]
