# Generated by Django 4.2.4 on 2024-03-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footnote',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footnote',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
