# Generated by Django 4.2.4 on 2024-03-26 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surah',
            options={'ordering': ['surah_number']},
        ),
        migrations.RemoveField(
            model_name='word',
            name='word_detail',
        ),
        migrations.AddField(
            model_name='word',
            name='prop_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='prop_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='prop_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='prop_4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='prop_5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='prop_6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='prop_7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='prop_8',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='related_surah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.surah', verbose_name='surah'),
        ),
        migrations.AlterField(
            model_name='footnote',
            name='translation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.translation', verbose_name='translation'),
        ),
        migrations.AlterField(
            model_name='root',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.word', verbose_name='word'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='book.verse'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='related_surah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.surah', verbose_name='surah'),
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
