# Generated by Django 4.2.4 on 2024-03-21 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_footnote_number_alter_footnote_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='footnote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.footnote', verbose_name='t_footnote'),
        ),
    ]
