# Generated by Django 4.2.4 on 2024-03-26 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_surah_options_remove_word_word_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootchars',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.root', verbose_name='character'),
        ),
    ]
