# Generated by Django 4.2.4 on 2024-03-27 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_word_arabic_alter_word_prop_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='root',
            name='word',
        ),
        migrations.AddField(
            model_name='word',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.root', verbose_name='words'),
        ),
    ]
