# Generated by Django 4.2.4 on 2024-03-28 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_root_word_word_root'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootChar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin', models.CharField(blank=True, max_length=5, null=True)),
                ('arabic', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.root', verbose_name='root'),
        ),
        migrations.DeleteModel(
            name='RootChars',
        ),
        migrations.AddField(
            model_name='root',
            name='char',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.rootchar', verbose_name='character'),
        ),
    ]
