# Generated by Django 4.2.4 on 2024-03-29 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_rootchar_alter_word_root_delete_rootchars_root_char'),
    ]

    operations = [
        migrations.CreateModel(
            name='Differential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.root', verbose_name='diffs')),
            ],
        ),
    ]
