# Generated by Django 4.2.4 on 2024-03-29 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_differential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='related_surah',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='book.surah', verbose_name='surah'),
        ),
        migrations.AlterField(
            model_name='differential',
            name='root',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='book.root', verbose_name='diffs'),
        ),
        migrations.AlterField(
            model_name='footnote',
            name='translation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='book.translation', verbose_name='translation'),
        ),
        migrations.AlterField(
            model_name='root',
            name='char',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='book.rootchar', verbose_name='character'),
        ),
        migrations.AlterField(
            model_name='surah',
            name='zero',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='book.versezero', verbose_name='zero_verse'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='book.author', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='verse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='translation', to='book.verse'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='related_surah',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='book.surah', verbose_name='surah'),
        ),
        migrations.AlterField(
            model_name='word',
            name='root',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='book.root', verbose_name='root'),
        ),
    ]
